database:
 url: jdbc:mysql://localhost:3306/property_src
 username: ketav
 password: S3cr3t1!
 driver:
  class: com.mysql.cj.jdbc.Driver


spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: ketav
   password: S3cr3t1!
   url: jdbc:mysql://localhost:3306/property_src

server:
  port: 8080
  servlet:
    context-path: /cloud-config-db
