database:
 url: jdbc:mysql://localhost:3306/property_src
 username: ketav
 password: 
 driver:
  class: com.mysql.cj.jdbc.Driver
 config:
  enabled: true
  select:
   query: select property_key, property_value from properties;

spring:
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: ketav
   password: 
   url: jdbc:mysql://localhost:3306/property_src

server:
  port: 8080
  servlet:
    context-path: /cloud-config-db
